Models/Member.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace FinalLastExam.Models
{
    public class Member:BaseEntity
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string? ImgUrl { get; set; }
        [NotMapped]
        public IFormFile? Image { get; set; }
    }
}

Areas/Admin/Controllers/MemberController.cs
using FinalLastExam.Areas.Admin.ViewModels;
using FinalLastExam.DAL;
using FinalLastExam.Helpers;
using FinalLastExam.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NuGet.Protocol.Plugins;

namespace FinalLastExam.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AutoValidateAntiforgeryToken]
    [Authorize]
    public class MemberController:Controller
    {
        
        private readonly AppDbContext _dbContext;
        private readonly IWebHostEnvironment _env;

        public MemberController(AppDbContext dbContext, IWebHostEnvironment env)
        {
            _dbContext = dbContext;
            _env = env;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            List<Member> members = await _dbContext.Members.ToListAsync();
            return View(members);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CreateMemberVM createMemberVM)
        {
            if (!ModelState.IsValid)
            {
                return View(createMemberVM);
            }

            if (!createMemberVM.Image.CheckLength(3000000))
            {
                ModelState.AddModelError("Image", " you can't upload more than 2 mb ");
                return View();
            }

            Member member = new Member()
            {
                Name = createMemberVM.Name,
                Work = createMemberVM.Work,
                ImgUrl = createMemberVM.Image.Upload(_env.WebRootPath, @"/Upload/Images/")
            };
            await _dbContext.Members.AddAsync(member);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int id)
        {
            if(id<=0) return View();
            Member member = await _dbContext.Members.Where(x => x.Id == id).FirstOrDefaultAsync();
            UpdateMemberVM updateMemberVM = new UpdateMemberVM()
            {
                Name=member.Name,
                Work=member.Work,
                ImgUrl = member.ImgUrl,
            };
            return View(updateMemberVM);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(UpdateMemberVM updateMemberVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (updateMemberVM.Id <= 0) throw new Exception("Id can't be less than zero");
            var member = _dbContext.Members.FirstOrDefault<Member>(x => x.Id == updateMemberVM.Id);
            if (member == null) throw new Exception("Fruit can't be null");


            member.Name = updateMemberVM.Name;
            member.Work = updateMemberVM.Work;
            member.ImgUrl = updateMemberVM.Image.Upload(_env.WebRootPath, @"/Upload/Images");
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");

        }
            [Authorize(Roles = "Admin")]
            public async Task<IActionResult> Delete(int id)
            {
                Member member = await _dbContext.Members.Where(x => x.Id == id).FirstOrDefaultAsync();
                 _dbContext.Members.Remove(member);
             await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Home");
            }
   }
}

Areas/Admin/Views/Member/Create.cshtml
@using FinalLastExam.Areas.Admin.ViewModels
@model CreateMemberVM

<div class="container"> 

<form method="post" enctype="multipart/form-data"> 
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for ="Name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <span asp-validation-for="Name" style="color:red"></span>
    </div>
        <div class="mb-3">
            <label asp-for="Work" class="form-label">Work</label>
            <input asp-for="Work" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <span asp-validation-for="Image" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Image" class="form-label">Multiple files input example</label>
            <input asp-for="Image"  id="formFileMultiple" multiple>
        </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

Areas/Admin/Views/Member/Index.cshtml
@using FinalLastExam.Models
@model List<Member> 
           
@{
    int count = 0;
}


<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    </p>
    <div>
    <a class="btn btn-primary" asp-action="Create" asp-controller="Member" >
        Create
    </a>
        </div>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Work</th>
                            <th>Image</th>
                            <th>Choises</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model)
                        {
                            count++;
                            <tr>
                            <td>@count</td>
                            <td> @item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Work</td>
                            <td></td>
                            <td>
                                <a class="btn btn-warning" asp-action="Update" asp-controller="Member" asp-route-id="@item.Id">
                                    Update
                                </a>
                                    <a class="btn btn-danger" asp-action ="Delete" asp-controller="Member" asp-route-id="@item.Id" >
                                        Delete
                                    </a>
                            </td>
                        </tr>

                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
            </div>
<!-- End of Main Content -->

Areas/Admin/Views/Member/Update.cshtml
@using FinalLastExam.Areas.Admin.ViewModels
@model UpdateMemberVM

<div class="container" >

    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <span asp-validation-for="Name" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Work" class="form-label">Work</label>
            <input asp-for="Work" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <span asp-validation-for="Image" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Image" class="form-label">Multiple files input example</label>
            <input asp-for="Image" type="file" id="formFileMultiple" multiple>
            <span asp-validation-for="Image" style="color:red"></span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>